### ISSUE TITLE
The steps are not clear enough ?

### ISSUE THREAD

**Issue by OceansAndThunders** [jfbeats/ArweaveWalletConnector#10]
Hello,

I'm a beginner at JS, and I find this tough to reproduce,
What I did is that I've run the command

```
npm i arweave-wallet-connector

```

then in the directory I made html file added that content :

```
<html>
<body>
<!--StartFragment-->

<script>
--
  | import { ArweaveWebWallet }
  |  
  | const wallet = new ArweaveWebWallet({
  | name: 'Connector Example',
  | logo: 'https://jfbeats.github.io/ArweaveWalletConnector/placeholder.svg'
  | })
  |  
  | wallet.setUrl('arweave.app')
  | await wallet.connect() // on user gesture to avoid blocked popup
  | </script>

<!--EndFragment-->
</body>
</html>
```

It was returning some error in the console, then I though this might be a nodeJS (as said I'm not good enough) and yet it's not working, I was poking around almost 4 hours
Can you please edit the readme.md with more clear "steps" and thanks in advance

**Comment by jfbeats** [comment]
Additional steps would be dependent on what you are using to build your app. For example there is a complete tutorial for react https://arwiki.wiki/#/en/creating-a-dapp
Not that I recommend using react specifically but I'd suggest starting from prebuilt project template or framework that let you use node modules directly
