### ISSUE TITLE
Should this library require the arweave-js library?

### ISSUE THREAD

**Issue by gxxcastillo** [jfbeats/ArweaveWalletConnector#9]
Hi, thanks for this library!  

I get this error when trying to build my web app and it prevents my app from building:

```
ERROR in ../../node_modules/arweave-wallet-connector/lib/Arweave.js 21:0-53
Module not found: Error: Can't resolve 'arweave/web/lib/transaction.js' in '.../node_modules/arweave-wallet-connector/lib'
```

If I manually add the arweave-js library with `yarn add arweave`, the error goes away.

**Comment by jfbeats** [comment]
Thanks for letting me know! Fixed on the new release 0.0.27, moved arweave-js from devDependencies to normal dependencies.

At first, it was only used at module build time to generate type guards, but I forgot to move it after I used it to create new Tag instances from the data returned by wallet providers when signing transactions
